resources:
  repositories:
    - repository: templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: expensely

trigger:
  batch: true
  branches:
    include:
      - "main"

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables/production.ap-southeast-2.yml@templates

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: postman_container
        displayName: Postman Container
        steps:
          - task: PowerShell@2
            displayName: Set build identifier
            name: setNPMBuildIdentifier
            inputs:
              targetType: inline
              script: Write-Host "##vso[build.updatebuildnumber]1.0.$(build.buildid)-$(System.StageAttempt)"
              errorActionPreference: default
              showWarnings: true
              pwsh: true
          - template: aws/iam/configure.yml@templates
          - template: ./docker/build.yml@templates
            parameters:
              target: lambda-postman
              workingDirectory: lambda
              arguments: "--build-arg BUILD_NUMBER=$(Build.BuildNumber)"
              tag: $(Build.BuildNumber)
          - template: ./aws/ecr/push.yml@templates
            parameters:
              imageName: lambda-postman
              repositoryName: lambda-postman
              tag: $(Build.BuildNumber)
